version: "3.9"

networks:
  ferrum:
  fg-base_ferrum:
    external: true


volumes:
  ferrum:
  lmdb:

services:
  prepare:
    image: alpine:3.17
    labels:
        FerrumGatewayId: "??GATEWAY_ID"
    command:
      - /bin/sh
      - -c
      - |
        CONF_FILE=/data/conf
        if [ ! -f $$CONF_FILE ];then
          echo "file does not exits"
          echo "FerrumGatewayId: "??GATEWAY_ID""> $$CONF_FILE
        fi
    networks:
      - ferrum
    volumes:
      - ferrum:/data
 

  server-ssh:
    image: "??PRIVATE_REGISTRY/ferrumgate/secure.server.quic:1.0.0"
    labels:
        FerrumGatewayId: "??GATEWAY_ID"
    restart: always
    ports:
      - "??SSH_PORT:9999/tcp"
      - "??SSH_PORT:9999/udp"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - PORT=9999
      - GATEWAY_ID=??GATEWAY_ID
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "registry.ferrumgate.zero:192.168.88.40"
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    depends_on:
      - prepare
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /dev/urandom:/dev/urandom
      - ferrum:/etc/ferrumgate
    networks:
      - ferrum
      - fg-base_ferrum
    logging:
      driver: local


  admin:
    image: "??PRIVATE_REGISTRY/ferrumgate/job.admin:1.11.0"
    labels:
        FerrumGatewayId: "??GATEWAY_ID"
    restart: always
    privileged: true
    #cap_add:
    #  - NET_ADMIN
    #  - MKNOD
    environment:
      - REDIS_HOST=${REDIS_PROXY_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_LOCAL_HOST=${REDIS_LOCAL_HOST}
      - REDIS_LOCAL_PASS=${REDIS_LOCAL_PASS}
      - REDIS_INTEL_HOST=${REDIS_INTEL_HOST}
      - REDIS_INTEL_PASS=${REDIS_INTEL_PASS}
      - FERRUM_IO_IMAGE=??PRIVATE_REGISTRY/ferrumgate/ferrum.io:1.4.0
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - GATEWAY_ID=??GATEWAY_ID
      - ES_HOST=${ES_PROXY_HOST}
      - ES_USER=${ES_USER}
      - ES_PASS=${ES_PASS}
      - LOG_LEVEL=${LOG_LEVEL}
      - SYSLOG_HOST=log:9292
      - DB_FOLDER=/var/lib/ferrumgate/db
    depends_on:
      - prepare
      - server-ssh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 5s
    volumes:
      - ferrum:/etc/ferrumgate
      - lmdb:/var/lib/ferrumgate
      - /etc/docker:/etc/docker
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: service:server-ssh
    logging:
      driver: local
 
  